#!/usr/bin/Rscript

input <- commandArgs(trailing = TRUE)[1]
sink("/dev/null")
library(knitr)
library(rmarkdown)
output <- sub("\\.[rR]?[mM][dD]", "\\.html", input, ignore.case = TRUE)
rmarkdown::render(input, output_file = output, quiet = TRUE, output_format = html_fragment(), encoding = "utf-8")
# suppressMessages(purl(input))
sink()
system(paste("cat", output))


# Rscript - e "library(rmarkdown); render(, output_format = html_fragment())"
